import type { ReactNode } from "react";
import { buildAppPath } from "../lib/basePath";

export type MarketingPageSlug = "home" | "privacy" | "support" | "terms";

export function marketingPageToPath(page: MarketingPageSlug) {
  switch (page) {
    case "privacy":
      return "/privacy";
    case "support":
      return "/support";
    case "terms":
      return "/terms";
    default:
      return "/";
  }
}

type MarketingPageProps = {
  onNavigate?: (page: MarketingPageSlug) => void;
};

type MarketingLinkProps = {
  page: MarketingPageSlug;
  children: ReactNode;
  onNavigate?: (page: MarketingPageSlug) => void;
  className?: string;
};

function MarketingLink({ page, children, onNavigate, className }: MarketingLinkProps) {
  const href = buildAppPath(marketingPageToPath(page));
  return (
    <a
      href={href}
      onClick={(event) => {
        if (onNavigate) {
          event.preventDefault();
          onNavigate(page);
        }
      }}
      className={className}
    >
      {children}
    </a>
  );
}

function MarketingLayout({
  heading,
  intro,
  children,
  onNavigate,
}: MarketingPageProps & {
  heading: string;
  intro: string;
  children: ReactNode;
}) {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-5">
          <div className="flex items-center gap-3">
            <img src="/iconnectit.png" alt="iTimedIT" className="h-10 w-10" />
            <div>
              <p className="text-xl font-semibold text-slate-800">iTimedIT</p>
              <p className="text-sm text-slate-500">Effortless professional time tracking</p>
            </div>
          </div>
          <nav className="flex flex-wrap items-center gap-4 text-sm font-medium text-slate-600">
            <MarketingLink page="home" onNavigate={onNavigate} className="hover:text-slate-900">
              Home
            </MarketingLink>
            <MarketingLink page="privacy" onNavigate={onNavigate} className="hover:text-slate-900">
              Privacy
            </MarketingLink>
            <MarketingLink page="support" onNavigate={onNavigate} className="hover:text-slate-900">
              Support
            </MarketingLink>
            <MarketingLink page="terms" onNavigate={onNavigate} className="hover:text-slate-900">
              Terms
            </MarketingLink>
          </nav>
        </div>
      </header>

      <main className="mx-auto flex max-w-4xl flex-col gap-10 px-6 py-16">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold text-slate-900">{heading}</h1>
          <p className="text-lg text-slate-600">{intro}</p>
        </div>
        <div className="space-y-12 text-slate-700">{children}</div>
      </main>

      <footer className="border-t border-slate-200 bg-slate-50">
        <div className="mx-auto flex max-w-5xl flex-col gap-4 px-6 py-6 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between">
          <p>© {new Date().getFullYear()} iTimedIT by iConnectIT. All rights reserved.</p>
          <div className="flex flex-wrap gap-4">
            <MarketingLink page="privacy" onNavigate={onNavigate} className="hover:text-slate-700">
              Privacy
            </MarketingLink>
            <MarketingLink page="support" onNavigate={onNavigate} className="hover:text-slate-700">
              Support
            </MarketingLink>
            <MarketingLink page="terms" onNavigate={onNavigate} className="hover:text-slate-700">
              Terms
            </MarketingLink>
          </div>
        </div>
      </footer>
    </div>
  );
}

export function PrivacyPolicyPage({ onNavigate }: MarketingPageProps) {
  return (
    <MarketingLayout
      heading="Privacy Policy"
      intro="We respect your privacy and are committed to protecting the personal data you share with iTimedIT."
      onNavigate={onNavigate}
    >
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Information We Collect</h2>
        <p>
          We collect information that you provide when creating an account, configuring your
          workspace, inviting team members, and recording time entries. This may include your name,
          contact details, organisation information, project metadata, and usage activity within the
          product.
        </p>
        <p>
          We also gather technical data such as device identifiers, browser type, IP address, and
          diagnostic logs generated by our services. These insights help us keep iTimedIT reliable
          and secure for every customer.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">How We Use Your Data</h2>
        <p>
          Personal information is used to deliver core product functionality, authenticate user
          access, and provide customer support. We analyse anonymised usage patterns so we can ship
          improvements that make teams more productive.
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Provide and maintain the iTimedIT platform and related integrations.</li>
          <li>Notify you about product updates, billing notices, and service announcements.</li>
          <li>Detect, prevent, and address technical issues or unauthorised access.</li>
          <li>Comply with legal obligations and enforce our terms of service.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Data Sharing &amp; Retention</h2>
        <p>
          We only share personal data with trusted subprocessors that power essential features such
          as hosting, authentication, and secure payments. Each partner signs agreements that mirror
          our privacy commitments.
        </p>
        <p>
          Your data is retained for as long as your organisation maintains an active subscription.
          When an account is cancelled, records are queued for deletion according to our retention
          schedules unless law requires otherwise.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Your Rights</h2>
        <p>
          Depending on your location, you may have rights to access, correct, export, or delete the
          information we hold about you. To submit a request, contact our team using the details on
          the Support page and we will respond promptly.
        </p>
        <p>
          If you believe your privacy has been impacted, please reach out immediately so we can
          investigate and resolve the issue.
        </p>
      </section>
    </MarketingLayout>
  );
}

export function SupportPage({ onNavigate }: MarketingPageProps) {
  return (
    <MarketingLayout
      heading="Support"
      intro="Need a hand with iTimedIT? Our support team is ready to help you keep work on track."
      onNavigate={onNavigate}
    >
      <section className="grid gap-8 md:grid-cols-2">
        <div className="space-y-3 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-slate-900">Email Support</h2>
          <p>
            Reach us directly at{" "}
            <a className="font-medium text-orange-600" href="mailto:kieran@iconnectit.co.uk">
              kieran@iconnectit.co.uk
            </a>{" "}
            for onboarding help, troubleshooting, or feature questions. We aim to respond within one
            business day.
          </p>
        </div>
        <div className="space-y-3 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-slate-900">Live Walkthroughs</h2>
          <p>
            Need a tailored demo for your team? Request a live walkthrough and we will coordinate a
            session to cover configuration, integrations, and best practices.
          </p>
        </div>
      </section>

      <section className="space-y-4">
        <h3 className="text-lg font-semibold text-slate-900">Helpful Resources</h3>
        <ul className="list-disc space-y-2 pl-5">
          <li>Step-by-step guides for configuring workspaces and inviting teammates.</li>
          <li>Best practices for tracking billable versus non-billable time.</li>
          <li>Tips for monitoring budgets and generating client-ready reports.</li>
        </ul>
        <p>
          We continuously add to our knowledge base so you can find answers at any hour. Let us know
          if there is a topic you would like to see covered.
        </p>
      </section>

      <section className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50 p-6">
        <h3 className="text-lg font-semibold text-slate-900">Incident Response</h3>
        <p>
          iTimedIT has monitoring in place to detect service issues quickly. In the unlikely event
          of downtime or degraded performance, we will publish updates to customers and work until
          full service is restored.
        </p>
      </section>
    </MarketingLayout>
  );
}

export function TermsPage({ onNavigate }: MarketingPageProps) {
  return (
    <MarketingLayout
      heading="Terms &amp; Conditions"
      intro="These terms outline the rules for using the iTimedIT platform provided by iConnectIT."
      onNavigate={onNavigate}
    >
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Using iTimedIT</h2>
        <p>
          By creating an account you confirm that you have authority to represent your organisation
          and that you will use the service in accordance with applicable laws. You agree to keep
          login credentials secure and notify us of any unauthorised access.
        </p>
        <p>
          You are responsible for the accuracy of time entries, project data, and client
          information stored within your workspace. We provide the tools; you maintain ownership of
          the content you create.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Subscriptions &amp; Billing</h2>
        <p>
          iTimedIT is offered on a subscription basis. Fees are payable in advance for each billing
          period and are non-refundable except where required by law. We may adjust pricing or plan
          features with reasonable notice.
        </p>
        <p>
          If payment cannot be processed, we will attempt to contact you. We reserve the right to
          suspend or terminate access for unpaid accounts.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Service Commitments</h2>
        <p>
          We work to keep iTimedIT available and performant. From time to time maintenance windows
          may be required; we will schedule these during low-usage periods whenever possible.
        </p>
        <p>
          The platform is provided on an “as-is” basis. While we strive for accuracy, we do not
          guarantee that the service will be uninterrupted or error-free. Our liability is limited
          to the fees paid for your current subscription term.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-900">Closing Your Account</h2>
        <p>
          You may cancel at any time by contacting our support team. Upon cancellation, access will
          continue until the end of the billing cycle unless otherwise agreed. We recommend
          exporting reports prior to closure for your records.
        </p>
        <p>
          These terms are updated from time to time. Continued use of iTimedIT after revisions take
          effect constitutes acceptance of the new conditions.
        </p>
      </section>
    </MarketingLayout>
  );
}
